//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InSpiderDevelopWindow.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InSpiderDevelopWindow.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddGroup 的本地化字符串。
        /// </summary>
        internal static string AddGroup {
            get {
                return ResourceManager.GetString("AddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Advance 的本地化字符串。
        /// </summary>
        internal static string Advance {
            get {
                return ResourceManager.GetString("Advance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 API 的本地化字符串。
        /// </summary>
        internal static string API {
            get {
                return ResourceManager.GetString("API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Api type 的本地化字符串。
        /// </summary>
        internal static string ApiType {
            get {
                return ResourceManager.GetString("ApiType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 bit invert 的本地化字符串。
        /// </summary>
        internal static string BitInvert {
            get {
                return ResourceManager.GetString("BitInvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Boolean value inversion 的本地化字符串。
        /// </summary>
        internal static string BitInvertefunTitle {
            get {
                return ResourceManager.GetString("BitInvertefunTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Both 的本地化字符串。
        /// </summary>
        internal static string Both {
            get {
                return ResourceManager.GetString("Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string CancelSave {
            get {
                return ResourceManager.GetString("CancelSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 you will be lost all data you have modify. To continue? 的本地化字符串。
        /// </summary>
        internal static string canceltosavemsg {
            get {
                return ResourceManager.GetString("canceltosavemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Channel 的本地化字符串。
        /// </summary>
        internal static string CommType {
            get {
                return ResourceManager.GetString("CommType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Communication 的本地化字符串。
        /// </summary>
        internal static string Communication {
            get {
                return ResourceManager.GetString("Communication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convert 的本地化字符串。
        /// </summary>
        internal static string Convert {
            get {
                return ResourceManager.GetString("Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConvertBack 的本地化字符串。
        /// </summary>
        internal static string ConvertBack {
            get {
                return ResourceManager.GetString("ConvertBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Make a express to convert &apos;Value&apos;  的本地化字符串。
        /// </summary>
        internal static string ConvertExpressTooltip {
            get {
                return ResourceManager.GetString("ConvertExpressTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DatabaseTagName 的本地化字符串。
        /// </summary>
        internal static string DatabaseTagName {
            get {
                return ResourceManager.GetString("DatabaseTagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DatabaseTagSelect 的本地化字符串。
        /// </summary>
        internal static string DatabaseTagSelect {
            get {
                return ResourceManager.GetString("DatabaseTagSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DatabaseToDevice 的本地化字符串。
        /// </summary>
        internal static string DatabaseToDevice {
            get {
                return ResourceManager.GetString("DatabaseToDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device 的本地化字符串。
        /// </summary>
        internal static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceToDatabase 的本地化字符串。
        /// </summary>
        internal static string DeviceToDatabase {
            get {
                return ResourceManager.GetString("DeviceToDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Direction 的本地化字符串。
        /// </summary>
        internal static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Driver 的本地化字符串。
        /// </summary>
        internal static string Driver {
            get {
                return ResourceManager.GetString("Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable 的本地化字符串。
        /// </summary>
        internal static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 erro 的本地化字符串。
        /// </summary>
        internal static string erro {
            get {
                return ResourceManager.GetString("erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Conversion formula 的本地化字符串。
        /// </summary>
        internal static string funTitle {
            get {
                return ResourceManager.GetString("funTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Some erro has happened,do you see erro.txt for detail? 的本地化字符串。
        /// </summary>
        internal static string ImportErroMsg {
            get {
                return ResourceManager.GetString("ImportErroMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import mode 的本地化字符串。
        /// </summary>
        internal static string ImportMode {
            get {
                return ResourceManager.GetString("ImportMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsAdmin 的本地化字符串。
        /// </summary>
        internal static string IsAdmin {
            get {
                return ResourceManager.GetString("IsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keyword 的本地化字符串。
        /// </summary>
        internal static string Keyword {
            get {
                return ResourceManager.GetString("Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 linear 的本地化字符串。
        /// </summary>
        internal static string Linear {
            get {
                return ResourceManager.GetString("Linear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Link 的本地化字符串。
        /// </summary>
        internal static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LinkType 的本地化字符串。
        /// </summary>
        internal static string LinkType {
            get {
                return ResourceManager.GetString("LinkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login 的本地化字符串。
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login failed! 的本地化字符串。
        /// </summary>
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logout 的本地化字符串。
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spider Studio 的本地化字符串。
        /// </summary>
        internal static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify 的本地化字符串。
        /// </summary>
        internal static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monitor 的本地化字符串。
        /// </summary>
        internal static string Monitor {
            get {
                return ResourceManager.GetString("Monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MonitorSetting 的本地化字符串。
        /// </summary>
        internal static string MonitorSetting {
            get {
                return ResourceManager.GetString("MonitorSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Project 的本地化字符串。
        /// </summary>
        internal static string NewProject {
            get {
                return ResourceManager.GetString("NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number2Bit 的本地化字符串。
        /// </summary>
        internal static string NumberToBit {
            get {
                return ResourceManager.GetString("NumberToBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Take one digit as the numerical value 的本地化字符串。
        /// </summary>
        internal static string NumberToBitfunTitle {
            get {
                return ResourceManager.GetString("NumberToBitfunTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm Password 的本地化字符串。
        /// </summary>
        internal static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Password 的本地化字符串。
        /// </summary>
        internal static string PasswordNew {
            get {
                return ResourceManager.GetString("PasswordNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste 的本地化字符串。
        /// </summary>
        internal static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project 的本地化字符串。
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PropertyCopy 的本地化字符串。
        /// </summary>
        internal static string PropertyCopy {
            get {
                return ResourceManager.GetString("PropertyCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PropertyPaste 的本地化字符串。
        /// </summary>
        internal static string PropertyPaste {
            get {
                return ResourceManager.GetString("PropertyPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Protocol 的本地化字符串。
        /// </summary>
        internal static string Protocol {
            get {
                return ResourceManager.GetString("Protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Publish 的本地化字符串。
        /// </summary>
        internal static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Publish 的本地化字符串。
        /// </summary>
        internal static string PublishString {
            get {
                return ResourceManager.GetString("PublishString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReadWriteMode 的本地化字符串。
        /// </summary>
        internal static string ReadWriteMode {
            get {
                return ResourceManager.GetString("ReadWriteMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Registor 的本地化字符串。
        /// </summary>
        internal static string Registor {
            get {
                return ResourceManager.GetString("Registor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RegistorConfig 的本地化字符串。
        /// </summary>
        internal static string RegistorConfig {
            get {
                return ResourceManager.GetString("RegistorConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reload 的本地化字符串。
        /// </summary>
        internal static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReName 的本地化字符串。
        /// </summary>
        internal static string ReName {
            get {
                return ResourceManager.GetString("ReName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 save failed! 的本地化字符串。
        /// </summary>
        internal static string Savefailed {
            get {
                return ResourceManager.GetString("Savefailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data is changed,do you want to save? 的本地化字符串。
        /// </summary>
        internal static string saveprompt {
            get {
                return ResourceManager.GetString("saveprompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 save sucessfull! 的本地化字符串。
        /// </summary>
        internal static string SaveSucessfull {
            get {
                return ResourceManager.GetString("SaveSucessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ScanCircle 的本地化字符串。
        /// </summary>
        internal static string ScanCircle {
            get {
                return ResourceManager.GetString("ScanCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selected 的本地化字符串。
        /// </summary>
        internal static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server 的本地化字符串。
        /// </summary>
        internal static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server 的本地化字符串。
        /// </summary>
        internal static string ServerIp {
            get {
                return ResourceManager.GetString("ServerIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Security 的本地化字符串。
        /// </summary>
        internal static string ServerSecurity {
            get {
                return ResourceManager.GetString("ServerSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify password failed. 的本地化字符串。
        /// </summary>
        internal static string SetPasswordfail {
            get {
                return ResourceManager.GetString("SetPasswordfail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify password secussfull. 的本地化字符串。
        /// </summary>
        internal static string SetPasswordSeccussful {
            get {
                return ResourceManager.GetString("SetPasswordSeccussful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ChannelShare 的本地化字符串。
        /// </summary>
        internal static string ShareChannel {
            get {
                return ResourceManager.GetString("ShareChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select channel shared device 的本地化字符串。
        /// </summary>
        internal static string ShareDeviceSelectTitle {
            get {
                return ResourceManager.GetString("ShareDeviceSelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome to spider 的本地化字符串。
        /// </summary>
        internal static string SpiderTitle {
            get {
                return ResourceManager.GetString("SpiderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run project 的本地化字符串。
        /// </summary>
        internal static string Start_Tooltip {
            get {
                return ResourceManager.GetString("Start_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop project 的本地化字符串。
        /// </summary>
        internal static string Stop_Tooltip {
            get {
                return ResourceManager.GetString("Stop_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 string formate 的本地化字符串。
        /// </summary>
        internal static string StringFormate {
            get {
                return ResourceManager.GetString("StringFormate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 String value format 的本地化字符串。
        /// </summary>
        internal static string StringFormatfunTitle {
            get {
                return ResourceManager.GetString("StringFormatfunTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tag count 的本地化字符串。
        /// </summary>
        internal static string TagCount {
            get {
                return ResourceManager.GetString("TagCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tag export complete! 的本地化字符串。
        /// </summary>
        internal static string TagExportComplete {
            get {
                return ResourceManager.GetString("TagExportComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query filter 的本地化字符串。
        /// </summary>
        internal static string TagFilter {
            get {
                return ResourceManager.GetString("TagFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tags 的本地化字符串。
        /// </summary>
        internal static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User 的本地化字符串。
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User List 的本地化字符串。
        /// </summary>
        internal static string UserList {
            get {
                return ResourceManager.GetString("UserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UserName 的本地化字符串。
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value 的本地化字符串。
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
    }
}
