//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cdy.Spider.ModbusDriver.Develop.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cdy.Spider.ModbusDriver.Develop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Address 的本地化字符串。
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DataSize 的本地化字符串。
        /// </summary>
        internal static string DataSize {
            get {
                return ResourceManager.GetString("DataSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DoubleFormate 的本地化字符串。
        /// </summary>
        internal static string DoubleFormate {
            get {
                return ResourceManager.GetString("DoubleFormate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FloatFormate 的本地化字符串。
        /// </summary>
        internal static string FloatFormate {
            get {
                return ResourceManager.GetString("FloatFormate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Id 的本地化字符串。
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IntFormate 的本地化字符串。
        /// </summary>
        internal static string IntFormate {
            get {
                return ResourceManager.GetString("IntFormate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LongFormate 的本地化字符串。
        /// </summary>
        internal static string LongFormate {
            get {
                return ResourceManager.GetString("LongFormate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Register batch configuration 的本地化字符串。
        /// </summary>
        internal static string ModbusMutiConfigTitle {
            get {
                return ResourceManager.GetString("ModbusMutiConfigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PackageLen 的本地化字符串。
        /// </summary>
        internal static string PackageLen {
            get {
                return ResourceManager.GetString("PackageLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Registor type 的本地化字符串。
        /// </summary>
        internal static string RegistorType {
            get {
                return ResourceManager.GetString("RegistorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repeat 的本地化字符串。
        /// </summary>
        internal static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ScanCircle 的本地化字符串。
        /// </summary>
        internal static string ScanCircle {
            get {
                return ResourceManager.GetString("ScanCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StringEncoding 的本地化字符串。
        /// </summary>
        internal static string StringEncoding {
            get {
                return ResourceManager.GetString("StringEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
    }
}
