//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cdy.Spider.CustomDriver.Develop.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cdy.Spider.CustomDriver.Develop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Apply 的本地化字符串。
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom driver 的本地化字符串。
        /// </summary>
        internal static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InitExpress 的本地化字符串。
        /// </summary>
        internal static string InitExpress {
            get {
                return ResourceManager.GetString("InitExpress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OnReceiveData 的本地化字符串。
        /// </summary>
        internal static string OnReceiveData {
            get {
                return ResourceManager.GetString("OnReceiveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OnSetValueToDevice 的本地化字符串。
        /// </summary>
        internal static string OnSetValueToDevice {
            get {
                return ResourceManager.GetString("OnSetValueToDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OnTimerProcess 的本地化字符串。
        /// </summary>
        internal static string OnTimerProcess {
            get {
                return ResourceManager.GetString("OnTimerProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Protocol 的本地化字符串。
        /// </summary>
        internal static string Protocol {
            get {
                return ResourceManager.GetString("Protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SaveAsTemplate 的本地化字符串。
        /// </summary>
        internal static string SaveAsTemplate {
            get {
                return ResourceManager.GetString("SaveAsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save as template sucuessful! 的本地化字符串。
        /// </summary>
        internal static string SaveAsTemplateSucessfull {
            get {
                return ResourceManager.GetString("SaveAsTemplateSucessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ScanCircle 的本地化字符串。
        /// </summary>
        internal static string ScanCircle {
            get {
                return ResourceManager.GetString("ScanCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ScriptCheck 的本地化字符串。
        /// </summary>
        internal static string ScriptCheck {
            get {
                return ResourceManager.GetString("ScriptCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Template 的本地化字符串。
        /// </summary>
        internal static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Template Name 的本地化字符串。
        /// </summary>
        internal static string TemplateFileName {
            get {
                return ResourceManager.GetString("TemplateFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Globel variable define 的本地化字符串。
        /// </summary>
        internal static string VariableDefine {
            get {
                return ResourceManager.GetString("VariableDefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WorkModel 的本地化字符串。
        /// </summary>
        internal static string WorkModel {
            get {
                return ResourceManager.GetString("WorkModel", resourceCulture);
            }
        }
    }
}
